###
PUT http://localhost:9200/testindex
Content-Type: application/json

###
POST http://localhost:9200/_opendistro/_ism/add/testindex
Content-Type: application/json

{
  "policy_id": "example"
}

###
GET localhost:9200/_opendistro/_ism/explain/testindex?show_applied_policy
Accept: application/json

###
GET localhost:9200/.opendistro-ism-config/_search
Accept: application/json

###

PUT localhost:9200/_opendistro/_ism/policies/example
Content-Type: application/json

{
  "policy": {
    "description": "ingesting logs",
    "default_state": "ingest",
    "states": [
      {
        "name": "ingest",
        "actions": [
          {
            "rollover": {
              "min_doc_count": 5
            }
          }
        ],
        "transitions": [
          {
            "state_name": "search"
          }
        ]
      },
      {
        "name": "search",
        "actions": [],
        "transitions": [
          {
            "state_name": "delete",
            "conditions": {
              "min_index_age": "5m"
            }
          }
        ]
      },
      {
        "name": "delete",
        "actions": [
          {
            "delete": {}
          }
        ],
        "transitions": []
      }
    ]
  }
}

###
DELETE localhost:9200/_opendistro/_ism/policies/example