<!--General Policy-->

###
PUT localhost:9200/_opendistro/_ism/policies/example
Content-Type: application/json

{
  "policy": {
    "description": "Example rollover policy.",
    "default_state": "rollover",
    "states": [
      {
        "name": "rollover",
        "actions": [
          {
            "rollover": {
              "min_doc_count": 1
            }
          }
        ],
        "transitions": []
      }
    ],
    "ism_template": {
      "index_patterns": ["log*", "testnoalias"],
      "priority": 100
    }
  }
}

###
DELETE localhost:9200/_opendistro/_ism/policies/example

###
<!--Index 1 missing alias-->

###
PUT http://localhost:9200/testnoalias
Content-Type: application/json

###
<!--EXPLAIN API-->

###
GET localhost:9200/_plugins/_ism/explain/testnoalias?pretty
Accept: application/json

###
<!--Add Alias-->

###
PUT http://localhost:9200/testnoalias/_alias/testalias
Content-Type: application/json

###
GET localhost:9200/_cat/aliases?v
Accept: application/json

###
PUT http://localhost:9200/_index_template/ism_rollover
Content-Type: application/json

{
  "index_patterns": ["testnoalias*"],
  "template": {
   "settings": {
    "plugins.index_state_management.rollover_alias": "testnoalias*"
   }
  }
}

###
GET localhost:9200/testnoalias/_settings
Accept: application/json


###
DELETE http://localhost:9200/testnoalias



<!--Index 2 not write index-->

###
PUT localhost:9200/_index_template/ism_rollover
Content-Type: application/json

{
  "index_patterns": ["log*"],
  "template": {
    "settings": {
      "plugins.index_state_management.rollover_alias": "log"
    }
  }
}

###
PUT localhost:9200/log-000002
Content-Type: application/json

{
  "aliases": {
    "log": {
      "is_write_index": false
    }
  }
}

###
PUT localhost:9200/log-000003
Content-Type: application/json

{
  "aliases": {
    "log": {
      "is_write_index": true
    }
  }
}

###
GET localhost:9200/_plugins/_ism/explain/log-000002?pretty
Accept: application/json

###
GET localhost:9200/_plugins/_ism/explain/log-000003?pretty
Accept: application/json

###
DELETE http://localhost:9200/log-000002

###
DELETE http://localhost:9200/log-000003
