name: Backward compatibility test workflow
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  test:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses the setup-java Github action: https://github.com/actions/setup-java
      - name: Set Up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 21
      # index-management
      - name: Checkout Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run IM Backwards Compatibility Tests
        run: |
          echo "Running backwards compatibility tests..."
          ./gradlew bwcTestSuite
      - name: Upload failed logs
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: failure()
        with:
          name: logs
          overwrite: 'true'
          path: build/testclusters/indexmanagementBwcCluster*/logs/*
