name: Link Checker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@649b0e4890508ea3e11ea6b3ee35ce899a25afd5 # master
        with:
          args: --accept=200,403,429  **/*.html **/*.md **/*.txt **/*.json
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
